version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  db:
    platform: linux/amd64
    build:
      context: "./db"
      dockerfile: "Dockerfile.arm"
    command: --default-authentication-plugin=mysql_native_password
    restart: always